export const REGISTER_USEROTP_REQUEST = "REGISTER_USEROTP_REQUEST";
export const REGISTER_USEROTP_SUCCESS = "REGISTER_USEROTP_SUCCESS";
export const REGISTER_USEROTP_FAIL = "REGISTER_USEROTP_FAIL";

export const LOGIN_USEROTP_REQUEST = "LOGIN_USEROTP_REQUEST";
export const LOGIN_USEROTP_SUCCESS = "LOGIN_USEROTP_SUCCESS";
export const LOGIN_USEROTP_FAIL = "LOGIN_USEROTP_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
